<Project Sdk="Aspire.AppHost.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>aspire-multirepo-remote-initialization</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Shirubasoft.Aspire.Extensions.Multirepo/Shirubasoft.Aspire.Extensions.Multirepo.csproj"
                      IsAspireProjectResource="false" />
  </ItemGroup>
</Project>
