<Project Sdk="Aspire.AppHost.Sdk/13.5.3">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>shirubasoft-aspire-extensions-kafka-sample</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Shirubasoft.Aspire.Extensions.Kafka/Shirubasoft.Aspire.Extensions.Kafka.csproj" IsAspireProjectResource="false" />
  </ItemGroup>
</Project>
